#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 04 10:48:58 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=\uFF08\u4E2D\u9AD8\u914D\uFF09Helian-MMCO.v1.0.1.Sundial.Lite.edit.zip
