#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 03 13:49:57 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=\uFF08\u4E2D\u4F4E\u914D\uFF09AuroraLite_v1.0.0.zip
